CREATE TABLE [ADPR].[Account_Compliance_Scope] (
    [ID]                                                     BIGINT          IDENTITY (1, 1) NOT NULL,
    [Parent_Accountid]                                       CHAR (15)       NULL,
    [Parent AccountName]                                     VARCHAR (50)    NULL,
    [Vertical]                                               VARCHAR (50)    NULL,
    [MARKET UNIT NAME]                                       VARCHAR (50)    NULL,
    [BU]                                                     VARCHAR (50)    NULL,
    [Yet to scope project #]                                 INT             NULL,
    [Available Hours]                                        DECIMAL (10, 2) NULL,
    [AD Project #]                                           INT             NULL,
    [AD Project -Overall #FTE]                               DECIMAL (10, 2) NULL,
    [AD Project-ADM FTE]                                     DECIMAL (10, 2) NULL,
    [AD- Overall #FTE with TSC %=0]                          DECIMAL (10, 2) NULL,
    [AD- Overall #FTE with TSC %>0 to 25]                    DECIMAL (10, 2) NULL,
    [AD- Overall #FTE with TSC %>25 to 50]                   DECIMAL (10, 2) NULL,
    [AD- Overall #FTE with TSC %>50 to 80]                   DECIMAL (10, 2) NULL,
    [AD- Overall #FTE with TSC %>80]                         DECIMAL (10, 2) NULL,
    [AD Project- ADM FTE with TSC %>80]                      DECIMAL (10, 2) NULL,
    [AD Project- Available Hours (All)]                      DECIMAL (10, 2) NULL,
    [AD Project- Available Hours (ADM)]                      DECIMAL (10, 2) NULL,
    [AD Project- Actual Effort (All)]                        DECIMAL (10, 2) NULL,
    [AD Project- Actual Effort (ADM)]                        DECIMAL (10, 2) NULL,
    [AD Scope - Account Effort Compliance% (All)]            DECIMAL (10, 2) NULL,
    [AD Scope - Account Associate Compliance% (All)]         DECIMAL (10, 2) NULL,
    [AD Scope - Account Effort Compliance% (ADM)]            DECIMAL (10, 2) NULL,
    [AD Scope - Account Associate Compliance% (ADM)]         DECIMAL (10, 2) NULL,
    [AM Project #]                                           INT             NULL,
    [AM Project -Overall #FTE]                               DECIMAL (10, 2) NULL,
    [AM Project-ADM FTE]                                     DECIMAL (10, 2) NULL,
    [AM- Overall #FTE with TSC %=0]                          DECIMAL (10, 2) NULL,
    [AM- Overall #FTE with TSC %>0 to 25]                    DECIMAL (10, 2) NULL,
    [AM- Overall #FTE with TSC %>25 to 50]                   DECIMAL (10, 2) NULL,
    [AM- Overall #FTE with TSC %>50 to 80]                   DECIMAL (10, 2) NULL,
    [AM- Overall #FTE with TSC %>80]                         DECIMAL (10, 2) NULL,
    [AM Project- ADM FTE with TSC %>80]                      DECIMAL (10, 2) NULL,
    [AM Project- Available Hours (All)]                      DECIMAL (10, 2) NULL,
    [AM Project- Available Hours (ADM)]                      DECIMAL (10, 2) NULL,
    [AM Project- Actual Effort (All)]                        DECIMAL (10, 2) NULL,
    [AM Project- Actual Effort (ADM)]                        DECIMAL (10, 2) NULL,
    [AM Scope - Account Effort Compliance% (All)]            DECIMAL (10, 2) NULL,
    [AM Scope - Account Associate Compliance% (All)]         DECIMAL (10, 2) NULL,
    [AM Scope - Account Effort Compliance% (ADM)]            DECIMAL (10, 2) NULL,
    [AM Scope - Account Associate Compliance% (ADM)]         DECIMAL (10, 2) NULL,
    [INTEGRATED Project #]                                   INT             NULL,
    [INTEGRATED Project -Overall #FTE]                       DECIMAL (10, 2) NULL,
    [INTEGRATED Project-ADM FTE]                             DECIMAL (10, 2) NULL,
    [INTEGRATED- Overall #FTE with TSC %=0]                  DECIMAL (10, 2) NULL,
    [INTEGRATED- Overall #FTE with TSC %>0 to 25]            DECIMAL (10, 2) NULL,
    [INTEGRATED- Overall #FTE with TSC %>25 to 50]           DECIMAL (10, 2) NULL,
    [INTEGRATED- Overall #FTE with TSC %>50 to 80]           DECIMAL (10, 2) NULL,
    [INTEGRATED- Overall #FTE with TSC %>80]                 DECIMAL (10, 2) NULL,
    [INTEGRATED Project- ADM FTE with TSC %>80]              DECIMAL (10, 2) NULL,
    [INTEGRATED Project- Available Hours (All)]              DECIMAL (10, 2) NULL,
    [INTEGRATED Project- Available Hours (ADM)]              DECIMAL (10, 2) NULL,
    [INTEGRATED Project- Actual Effort (All)]                DECIMAL (10, 2) NULL,
    [INTEGRATED Project- Actual Effort (ADM)]                DECIMAL (10, 2) NULL,
    [INTEGRATED Scope - Account Effort Compliance% (All)]    DECIMAL (10, 2) NULL,
    [INTEGRATED Scope - Account Associate Compliance% (All)] DECIMAL (10, 2) NULL,
    [INTEGRATED Scope - Account Effort Compliance% (ADM)]    DECIMAL (10, 2) NULL,
    [INTEGRATED Scope - Account Associate Compliance% (ADM)] DECIMAL (10, 2) NULL
);

