CREATE TABLE [ADPR].[Project_Compliance_Monthly] (
    [ID]                                       BIGINT          IDENTITY (1, 1) NOT NULL,
    [Parent_Accountid]                         FLOAT (53)      NULL,
    [Parent_AccountName]                       VARCHAR (100)   NULL,
    [EsaProjectid]                             CHAR (15)       NULL,
    [ProjectName]                              VARCHAR (100)   NULL,
    [SBU]                                      VARCHAR (50)    NULL,
    [PO ID]                                    VARCHAR (100)   NULL,
    [PO Name]                                  VARCHAR (100)   NULL,
    [DM ID]                                    VARCHAR (100)   NULL,
    [DM Name]                                  VARCHAR (100)   NULL,
    [PM ID]                                    VARCHAR (100)   NULL,
    [PM Name]                                  VARCHAR (100)   NULL,
    [Project_Department]                       VARCHAR (100)   NULL,
    [DE_Inscope]                               VARCHAR (100)   NULL,
    [Overall #FTE]                             DECIMAL (10, 2) NULL,
    [AVM #FTE]                                 DECIMAL (10, 2) NULL,
    [Overall #FTE with TSC %=0]                DECIMAL (10, 2) NULL,
    [Overall #FTE with TSC %>0 to 25]          DECIMAL (10, 2) NULL,
    [Overall #FTE with TSC %>25 to 50]         DECIMAL (10, 2) NULL,
    [Overall #FTE with TSC %>50 to 80]         DECIMAL (10, 2) NULL,
    [Overall #FTE with TSC %>80]               DECIMAL (10, 2) NULL,
    [AVM #FTE with TSC %>80]                   DECIMAL (10, 2) NULL,
    [Available Hours]                          DECIMAL (10, 2) NULL,
    [Available Hours AVM]                      DECIMAL (10, 2) NULL,
    [Actual Effort]                            DECIMAL (10, 2) NULL,
    [Actual Effort_AVM]                        DECIMAL (10, 2) NULL,
    [Effort Project Compliance% (All)]         DECIMAL (10, 2) NULL,
    [Associate_Project_Compliance_Percent]     DECIMAL (10, 2) NULL,
    [Effort Project Compliance% (AVM)]         DECIMAL (10, 2) NULL,
    [AVM Associate_Project_Compliance_Percent] DECIMAL (10, 2) NULL,
    [Startdate]                                DATETIME        NULL,
    [Enddate]                                  DATETIME        NULL,
    [Created datetime]                         DATETIME        NULL,
    [MARKETUNITNAME]                           NVARCHAR (100)  NULL
);

